"""Semantic fixture corpus structure and the deterministic test adapter's
recall characterization (todo_validation item 6).

Two responsibilities:

1. Corpus integrity — the labelled fixtures cover every required semantic
   category, bind only valid option/participant ids, keep claim spans exact,
   and distinguish public commitment from ordinary preference.

2. Recall ratchet — for each fixture, project the expected evidence onto what
   the deterministic test adapter (tests/evidence_adapter.py) produces and
   compare with a pinned known-gaps table. The gaps document exactly which
   natural-language shapes REQUIRE the validator LLM's recall; validator-side
   coverage of the same corpus lives in tests/test_interpreter.py.
"""

from __future__ import annotations

import unittest

from models import VisibleEvidence
from parsing import OptionResolver, visible_commitment
from tests import semantic_fixtures as sf
from tests.evidence_adapter import derive_evidence
from tests.fixtures import make_resolver, make_scenario

VALID_OPTIONS = {"A", "B", "C"}
VALID_PARTICIPANTS = {"p1", "p2", "p3"}

_NAMES = {"p1": "Mira", "p2": "Jonas", "p3": "Lea"}


def _project_gaps(fixture: sf.SemanticFixture) -> tuple[VisibleEvidence, set[str]]:
    """Expected evidence the deterministic test adapter fails to produce.

    The adapter's recall equals the old conservative parser's, so this table
    documents exactly which fixtures REQUIRE the validator LLM's recall."""
    resolver = make_resolver()
    evidence = derive_evidence(
        fixture.text, resolver,
        speaker_id=fixture.speaker_id,
        participant_names=_NAMES,
        previous_speaker_id=fixture.context_speaker_id if fixture.context_text else None,
    )
    gaps: set[str] = set()

    commit = evidence.sole_commitment()
    if fixture.commitment:
        _, option = fixture.commitment
        if commit is None or commit.option_id != option:
            gaps.add(f"commitment:{option}")
    elif commit is not None:
        gaps.add(f"false_commitment:{commit.option_id}")

    concern_bindings = {(c.option_id, c.severity) for c in evidence.concerns}
    for option, severity in fixture.concerns:
        if severity == sf.CONCERN_ORDINARY and (option, "ordinary") not in concern_bindings:
            gaps.add(f"concern:{option}")
        if severity == sf.CONCERN_HARD and (option, "hard") not in concern_bindings:
            gaps.add(f"hard_rejection:{option}")

    raised = {b.option_id for b in evidence.blockers if b.action == "raised"}
    resolved = {b.option_id for b in evidence.blockers if b.action == "resolved"}
    if fixture.blocker_raised and fixture.blocker_raised not in raised:
        gaps.add(f"blocker:{fixture.blocker_raised}")
    if fixture.blocker_resolved and fixture.blocker_resolved not in resolved:
        gaps.add(f"blocker_resolution:{fixture.blocker_resolved}")
    if fixture.softens_toward and fixture.softens_toward not in {
        s.option_id for s in evidence.softenings
    }:
        gaps.add(f"softening:{fixture.softens_toward}")
    if fixture.proposes and fixture.proposes not in {p.option_id for p in evidence.proposals}:
        gaps.add(f"proposal:{fixture.proposes}")

    direct = {q.addressee_id for q in evidence.questions if q.scope == "direct"}
    group = any(q.scope == "group" for q in evidence.questions)
    for question in fixture.questions:
        if question.scope == sf.Q_DIRECT:
            if question.addressee not in direct:
                gaps.add(f"question_direct:{question.addressee}")
        elif question.scope == sf.Q_GROUP:
            if not group:
                gaps.add("question_group")
        elif question.scope == sf.Q_RHETORICAL and evidence.questions:
            gaps.add("rhetorical_as_question")

    if fixture.comparisons and not evidence.comparisons:
        gaps.add("comparison")

    supports = {(s.option_id, s.strength) for s in evidence.supports}
    supported_options = {option for option, _strength in supports}
    for option, strength in fixture.support:
        if strength == sf.SUPPORT_CONDITIONAL:
            if (option, "conditional") not in supports:
                gaps.add(f"conditional_support:{option}")
        elif option not in supported_options:
            gaps.add(f"support:{option}")

    if fixture.ambiguous_reference and (evidence.commitments or evidence.concerns):
        gaps.add("ambiguous_reference_bound")

    return evidence, gaps


# What the deterministic test adapter is known NOT to extract from the corpus.
# Every entry is a real, reproduced gap (generated by running the projection);
# these shapes need the validator LLM's recall at runtime.
KNOWN_CURRENT_GAPS: dict[str, set[str]] = {
    "support_indirect": {"support:A"},
    "support_weak": {"support:B"},
    "support_firm": {"support:B"},
    "concern_natural_hesitant": {"concern:C"},
    # NOTE: the current parser labels this line as SUPPORT for A ("gives" is a
    # pro-claim verb) — the concern is not just missed, it is inverted.
    "concern_natural_pause": {"concern:A"},
    "compare_balanced": {"comparison"},
    "compare_key_difference": {"comparison"},
    "compare_question": {"comparison"},
    "ask_rhetorical": {"concern:C"},
    "answer_unrelated": {"support:A"},
    "soften_natural": {"softening:A"},
    "concession_priority": {"support:A"},
    "vote_menuless_has_my_vote": {"commitment:B"},
    "vote_menuless_backing": {"commitment:B"},
    "vote_menuless_put_me_down": {"commitment:C"},
    "preference_worth_considering": {"support:B"},
    "preference_lean": {"support:A"},
    # The trailing group question currently voids the visible vote commitment,
    # and "dislike" is outside the concern vocabulary.
    "switch_with_reason_multi": {"commitment:B", "concern:A"},
    "pronoun_clear": {"concern:C"},
    "fact_cross_option": {"concern:B"},
    "opinion_fun": {"support:C"},
}


class CorpusStructure(unittest.TestCase):
    def test_fixture_ids_unique(self) -> None:
        ids = [f.fixture_id for f in sf.FIXTURES]
        self.assertEqual(len(ids), len(set(ids)))

    def test_every_required_category_is_covered(self) -> None:
        covered = {f.category for f in sf.FIXTURES}
        missing = [c for c in sf.REQUIRED_CATEGORIES if c not in covered]
        self.assertEqual(missing, [])

    def test_only_known_categories_used(self) -> None:
        allowed = set(sf.REQUIRED_CATEGORIES)
        self.assertEqual([f.fixture_id for f in sf.FIXTURES if f.category not in allowed], [])

    def test_option_and_participant_ids_are_valid(self) -> None:
        for fixture in sf.FIXTURES:
            bound: list[str | None] = [option for option, _ in fixture.support]
            bound += [option for option, _ in fixture.concerns]
            for comparison in fixture.comparisons:
                bound += list(comparison.options)
                bound.append(comparison.favored)
            for question in fixture.questions:
                bound += list(question.options)
                if question.addressee is not None:
                    self.assertIn(question.addressee, VALID_PARTICIPANTS, fixture.fixture_id)
            if fixture.commitment:
                bound.append(fixture.commitment[1])
            if fixture.switch:
                bound += [fixture.switch.source, fixture.switch.target]
            bound += [fixture.softens_toward, fixture.proposes,
                      fixture.blocker_raised, fixture.blocker_resolved]
            bound += list(fixture.context_resolved_options)
            bound += [claim.option for claim in fixture.claims]
            for option in bound:
                if option is not None:
                    self.assertIn(option, VALID_OPTIONS, fixture.fixture_id)
            self.assertIn(fixture.speaker_id, VALID_PARTICIPANTS, fixture.fixture_id)
            if fixture.context_text:
                self.assertIn(fixture.context_speaker_id, VALID_PARTICIPANTS, fixture.fixture_id)

    def test_claim_spans_are_exact_substrings(self) -> None:
        for fixture in sf.FIXTURES:
            for claim in fixture.claims:
                self.assertIn(claim.span, fixture.text, fixture.fixture_id)

    def test_multi_function_fixtures_exist(self) -> None:
        multi = [f for f in sf.FIXTURES if len(f.evidence_kinds()) >= 2]
        self.assertGreaterEqual(len(multi), 5, [f.fixture_id for f in multi])

    def test_commitment_is_distinct_from_preference(self) -> None:
        for fixture in sf.FIXTURES:
            if fixture.category == "preference_not_vote":
                self.assertIsNone(fixture.commitment, fixture.fixture_id)
                self.assertTrue(fixture.support, fixture.fixture_id)
            if fixture.category in {"vote_direct", "vote_menuless"}:
                self.assertIsNotNone(fixture.commitment, fixture.fixture_id)

    def test_grounding_claim_kinds_all_represented(self) -> None:
        kinds = {claim.kind for fixture in sf.FIXTURES for claim in fixture.claims}
        required = {
            sf.CLAIM_LISTED_FACT, sf.CLAIM_ARITHMETIC, sf.CLAIM_OPINION,
            sf.CLAIM_INFERENCE, sf.CLAIM_UNCERTAINTY, sf.CLAIM_INVENTED,
            sf.CLAIM_CROSS_OPTION,
        }
        self.assertEqual(required - kinds, set())

    def test_fixture_texts_resolve_against_standard_scenario(self) -> None:
        # Explicit option mentions in fixture texts must be resolvable with the
        # standard scenario's aliases (bare labels like "B" are intentionally
        # unresolvable today; those fixtures rely on the future label support).
        resolver = OptionResolver(make_scenario().options)
        self.assertEqual(resolver.ids_in_text("the Museum"), ["A"])
        self.assertEqual(resolver.ids_in_text("the Bike Ride"), ["B"])
        self.assertEqual(resolver.ids_in_text("the Escape Room"), ["C"])


class AdapterRecallCharacterization(unittest.TestCase):
    def test_adapter_gaps_match_pinned_table(self) -> None:
        for fixture in sf.FIXTURES:
            _, gaps = _project_gaps(fixture)
            expected = KNOWN_CURRENT_GAPS.get(fixture.fixture_id, set())
            self.assertEqual(
                gaps, expected,
                f"{fixture.fixture_id}: deterministic adapter gaps changed "
                f"(got {sorted(gaps)}, pinned {sorted(expected)})",
            )

    def test_no_stale_known_gap_entries(self) -> None:
        fixture_ids = {f.fixture_id for f in sf.FIXTURES}
        self.assertEqual(set(KNOWN_CURRENT_GAPS) - fixture_ids, set())

    def test_preference_fixtures_never_commit(self) -> None:
        # Safety-critical: the conservative commitment layer must not produce a
        # vote/acceptance from mere preference wording.
        resolver = make_resolver()
        for fixture in sf.FIXTURES:
            if fixture.commitment is None:
                commit = visible_commitment(fixture.text, resolver)
                self.assertTrue(
                    commit is None or commit[0] == "reject", fixture.fixture_id
                )


if __name__ == "__main__":
    unittest.main()
